import { Link } from "react-router-dom";
import { useContext } from "react";
import { FilterContext } from "./contexts/FilterContext";

// Generated by claude.ai
const GENRE_COLORS = [
  "from-blue-500 to-blue-900",
  "from-purple-500 to-purple-900",
  "from-pink-500 to-pink-900",
  "from-red-500 to-red-900",
  "from-orange-500 to-orange-900",
  "from-yellow-500 to-yellow-900",
  "from-green-500 to-green-900",
  "from-teal-500 to-teal-900",
  "from-cyan-500 to-cyan-900",
  "from-indigo-500 to-indigo-900",
  "from-violet-500 to-violet-900",
  "from-fuchsia-500 to-fuchsia-900",
  "from-rose-500 to-rose-900",
  "from-lime-500 to-lime-900",
  "from-emerald-500 to-emerald-900",
  "from-sky-500 to-sky-900",
  "from-amber-500 to-amber-900",
  "from-slate-500 to-slate-900",
  "from-zinc-500 to-zinc-900",
  "from-stone-500 to-stone-900",
];

const GenreCard = ({ genre }) => {
  const colorClass = GENRE_COLORS[genre.genre_id % GENRE_COLORS.length];
  const { toggleFilter } = useContext(FilterContext);
  return (
    <Link
      to="/songs"
      className="rounded-xl overflow-hidden cursor-pointer hover:scale-105 transition-transform will-change-transform duration-200 shadow-xl/15"
      onClick={() => toggleFilter("genres", genre.genre_name)}
    >
      <div className={`bg-radial ${colorClass} h-36 w-full`} />

      <div className="bg-gray-800 px-4 py-3">
        <p className="text-white font-semibold capitalize">
          {genre.genre_name}
        </p>
      </div>
    </Link>
  );
};

export default GenreCard;
